# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    working_dir: '/var/www/html'
    volumes:
      - ${PWD}/www-data:/var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: my_wiki
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_wiki
    ports:
        - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
